# Generated by Django 3.2.25 on 2024-09-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='is_request',
            field=models.BooleanField(default=True),
        ),
    ]
