# Generated by Django 3.2.25 on 2024-09-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_friendship_user_friend_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('RU', 'Russian'), ('FI', 'Finnish'), ('EN', 'English')], default='EN', max_length=2),
        ),
    ]
