# Generated by Django 3.2.25 on 2024-09-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20240915_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttournament',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Completed'), (3, 'DElete')], default=0),
        ),
    ]
