services:
  dev:
    image: dev
    container_name: dev
    build:
      context: dev
      dockerfile: Dockerfile
#    pull_policy: build
    networks:
      - t_extra
    volumes:
      - ./dev/src:/app/src
    ports:
      - "5173:5173"

  # server:
  #   image: server
  #   container_name: server
  #   build:
  #     context: server
  #     dockerfile: Dockerfile
  #   pull_policy: build
  #   networks:
  #     - t_extra
  #   volumes:
  #     - ./server/src:/app/src
  #   ports:
  #     - "5174:5173"
  #     - "8001:8001"

  mpdev:
    image: mpdev
    container_name: mpdev
    build:
      context: mpdev
      dockerfile: Dockerfile
    networks:
      - t_extra
    volumes:
      - ./mpdev/src:/app/src
    ports:
      - "5000:5000"
      - "6000:6000"

networks:
  t_intra:
    name: t_intra
  t_extra:
    name: t_extra