services:
  mpdev:
    image: mpdev
    container_name: mpdev
    build:
      context: mpdev
      dockerfile: Dockerfile
    networks:
      - t_extra
    volumes:
      - ./mpdev/src:/app/src
    ports:
      - "7000:7000"

networks:
  t_intra:
    name: t_intra
  t_extra:
    name: t_extra
