version: '3.5'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: pong_project
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
       - t_intra


  backend:
    image: backend
    container_name: backend
    build: ./backend
    depends_on:
      - db
    networks:
      - t_intra
      - t_extra
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=pong_project
      - DATABASE_USER=your_user
      - DATABASE_PASSWORD=your_password

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    pull_policy: build
    networks:
      - t_extra
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://backend:8000 


networks:
  t_intra:
    name: t_intra
  t_extra:
    name: t_extra

volumes:
  postgres_data: